name: Documentation Build and Deploy CI

on:
  push:
    branches:
    - master
    - release/*
    paths:
    - 'docs_espressif/**'
    - '.github/workflows/docs_build.yml'
  pull_request:
    paths:
    - 'docs_espressif/**'
    - '.github/workflows/docs_build.yml'

jobs:

  build-docs:
    name: Build ESP-IDF VSCode Extension Docs
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-python@v5
      with:
        cache-dependency-path: docs_espressif/requirements.txt
        cache: 'pip'
        python-version: '3.10'
    - name: Build
      run: |
        sudo apt update
        sudo apt install python3-pip python3-setuptools
        # GitHub CI installs pip3 and setuptools outside the path.
        # Update the path to include them and run.
        cd ./docs_espressif
        PATH=/home/runner/.local/bin:$PATH pip3 install -r requirements.txt --prefer-binary
        PATH=/home/runner/.local/bin:$PATH SPHINXOPTS="-W" build-docs -l en
    - name: Archive Docs
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs
    - name: Deploy Documentation to preview server
      env:
        # Deploy to production server
        # DOCS_BUILD_DIR: "./docs_espressif/_build/"
        DOCS_DEPLOY_PRIVATEKEY: ${{ secrets.DOCS_PREVIEW_PRIVATEKEY }}
        DOCS_DEPLOY_PATH: ${{ secrets.DOCS_PREVIEW_PATH }}
        DOCS_DEPLOY_SERVER: ${{ secrets.DOCS_PREVIEW_SERVER }}
        DOCS_DEPLOY_SERVER_USER: ${{ secrets.DOCS_PREVIEW_USER }}
        DOCS_DEPLOY_URL_BASE: ${{ secrets.DOCS_PREVIEW_URL_BASE }}
      run: |
        sudo apt update
        sudo apt install python3-pip python3-setuptools
        source ./docs_espressif/utils.sh
        add_doc_server_ssh_keys $DOCS_DEPLOY_PRIVATEKEY $DOCS_DEPLOY_SERVER $DOCS_DEPLOY_SERVER_USER
        export GIT_VER=$(git describe --always)
        echo "PIP install requirements..."
        pip3 install --user -r ./docs_espressif/requirements.txt
        echo "Building the Docs..."
        cd ./docs_espressif && build-docs -l en
        echo "Deploy the Docs..."
        export DOCS_BUILD_DIR=$GITHUB_WORKSPACE/docs/
        cd $GITHUB_WORKSPACE/docs
        deploy-docs